import styles from './Historia5.module.css'
import Getulio from '../../img/getulio.png'


function Historia5(){
    return(
        <section className={styles.home_container}>
            <h1>Getúlio Vargas, a Petrobrás e o silêncio dos militares</h1>
            <img src={Getulio} alt=""></img>
            <p>Neste sábado, o Brasil relembra os 65 anos da morte de Getúlio Vargas. O presidente da República mais influente e popular do Brasil no século 20 tirou a vida na madrugada de 24 de agosto de 1954. O gesto dramático – um tiro no peito – foi o último esforço para barrar a sanha golpista que varria o Brasil naquele período. Sua morte mudou o curso da história do país, adiou o golpe por quase 10 anos e alterou radicalmente a cena política brasileira.</p>
            <p>Não há paralelo para a importância de Getúlio Vargas na história do país. Foi ele quem criou o moderno Estado brasileiro, ao fundar a Petrobrás e a Eletrobrás, criar a Companhia Siderúrgica Nacional e estabelecer um marco legal para a relação entre capital e trabalho. Foi ele quem criou as bases do Brasil democrático, mesmo tendo sido um ditador na década de 30.</p>
            <p>O ideário de Vargas, de tornar o Brasil uma nação moderna, com justiça social e oportunidade para todos, parece distante. A sensação é agravada pelos retrocessos do presente. O presidente Jair Bolsonaro é responsável por este presente feio, disruptivo, intimidador, antidemocrático e entreguista. O presente das queimadas, do desmatamento, da fome nas cidades e da violência nas ruas. O presente das privatizações e da entrega do patrimônio público. O Brasil assiste, atônito, a um governo cujo único propósito é destruir a débil política de bem-estar social, desenhada pela Carta de 1988 e golpeada em 2016 pelo impeachment fraudulento de Dilma Rousseff.</p>
            <p>Bolsonaro quer entregar nossas riquezas e se colocar na posição subalterna ante os Estados Unidos. Faz um governo para atacar a soberania, ignora o sofrimento do povo e arranca do orçamento qualquer investimento em saúde, educação e cultura. Em nome do mercado, promete entregar empresas como a Eletrobrás e a Petrobrás.</p>
            <h3>ALVO É O PETRÓLEO</h3>
            <p>Precisamos ter clareza: o petróleo é o alvo. O Brasil hoje acumula mais de US$ 1 trilhão em reservas de petróleo apenas no pré-sal. Em maio, bateu recorde de produção diária de petróleo e gás de quase 3,5 milhões de barris de petróleo equivalente. Mesmo com todos os problemas recentes e sofrendo toda sorte de ataques, a Petrobras está entre as 10 maiores petrolíferas do mundo. É patrimônio do povo brasileiro. Não pode ser usada como instrumento de destruição da economia e da soberania nacional. A política de desinvestimento da Petrobras, com a entrega de subsidiárias, é um erro. E não apenas estratégico, mas porque os valores são ridículos. O Congresso é ignorado e as vendas são anunciadas sem discussão no Parlamento. Assim, venderam redes de gasodutos, no Nordeste e no Sudeste, por US$ 15 bilhões. Entregaram o controle da BR Distribuidora por R$ 8,6 bilhões. E pretendem imolar oito refinarias por US$ 20 bilhões. É pouco.</p>
            <p>Pior. Paulo Guedes já fala abertamente na privatização da empresa e Roberto Castello Branco escancara o próximo ato antes da entrega do botim: o fim do regime de partilha do pré-sal. Não é possível que o agronegócio, a indústria e os militares não vejam o potencial destrutivo do desmanche promovido na Petrobras. Fala-se pouco, mas é preciso ter clareza. A disputa por petróleo é o que define a geopolítica no mundo. É por causa do petróleo e do pré-sal que Dilma Rousseff e a Petrobras foram alvos de espionagem da NSA, a agência de segurança dos Estados Unidos.</p>
            <p>É por causa do petróleo e do pré-sal que a Lava Jato, sob a desculpa de travar uma guerra contra a corrupção, atacou a própria Petrobras, induzindo-a a forjar um acordo com o Departamento de Justiça americano, obrigando-a a pagar R$ 2,5 bilhões para um fundo privado, além de multa de US$ 682,5 milhões a investidores americanos. Um escândalo.</p>
            <h3>CONSUMO E RESERVAS  </h3>
            <p>O ouro negro é o que mantém girando a roda da economia mundial. A cada ano, o mundo bate recorde no consumo de petróleo. Em 2019, o consumo vai superar a marca diária de 100 milhões de barris. E poucas nações têm reservas para enfrentar um futuro que assegure um caminho de desenvolvimento econômico e social. A Venezuela é hoje o país com as maiores reservas do mundo: 300,9 bilhões de barris. O segundo é a Arábia Saudita, com 266,5 bilhões de barris. O Canadá está em terceiro, com 169,7 bilhões de barris. O Brasil aparece na 15ª posição, com 12,7 bilhões de barris. E nem esgotamos as pesquisas em campos a serem descobertos nos mares brasileiros.</p>
            <p>O pré-sal é a última fronteira de petróleo a ser explorada no mundo nas próximas décadas. Este é o tabuleiro da guerra assimétrica que o Brasil enfrenta. Nada mal para quem nos anos 50 tinha poucos poços de petróleo em regiões do sertão nordestino e em Cubatão. Hoje está entre as 10 maiores produtoras do mundo.</p>
            <p>Tal resultado não é banal. Veio com esforço, empenho de homens e mulheres, pesquisadores, engenheiros, trabalhadores, patriotas e chefes de Estado – como Getúlio, Lula e Dilma Rousseff. Gente com visão de país e projeto para o povo. Isso tudo é fruto da ação do Estado brasileiro. Este mesmo Estado que Paulo Guedes e Bolsonaro sonham em destruir de maneira afrontosa.</p>
            <h3>PAPEL DO EXÉRCITO</h3>
            <p>O futuro que se avizinha com este governo é sombrio. E isso ocorre, ironicamente, com o governo com o maior número de autoridades egressas das Forças Armadas e o próprio presidente da República é um capitão do Exército. Este mesmo Exército que foi vital para tirar a Petrobras do papel ainda nos anos 40 e transformá-la na maior empresa do Brasil e numa das mais importantes do mundo.</p>
            <p>Vale lembrar que o sonho da Petrobras nasceu dentro do Exército. Em 1938, o Estado Maior das Forças Armadas foi quem primeiro apontou a necessidade de uma política para o petróleo, propondo o monopólio estatal. Em 29 de abril de 1938, Getúlio Vargas criou o Conselho Nacional do Petróleo, restringindo o refino de óleo a empresas formadas por brasileiros natos. O primeiro presidente do conselho foi o General Horta Barbosa. Foi quando o petróleo jorrou no país pela primeira vez, em 1939, em Lobato, na Bahia. Também foi sob a liderança deste militar que foram iniciados estudos para a refinaria de Mataripe, também na Bahia.</p>
            <p>O que hoje é realidade palpável em reservas robustas de petróleo parecia uma miragem há 70 anos. Em novembro de 1942, o Brasil só se convenceu de que havia farto petróleo no país quando o jornalista Samuel Wainer, na revista Diretrizes, entrevistou o geólogo Glen Ruby. E este americano, responsável pela descoberta de petróleo na Terra do Fogo, abriu o jogo: “Existe muito petróleo no Brasil”. E advertiu: “Só as nações que controlam sua energia podem controlar seu destino”.</p>
            <p><strong>HISTÓRIA DE LUTA</strong></p>
            <p>Entre 1945 e 1953, quando Getúlio criou a Petrobrás, foi pela ação dos militares que o sonho de o Brasil desenvolver uma indústria de petróleo deixou de ser miragem e passou a ser possível. Em 1947, o Clube Militar deflagrava um movimento contrário a abertura do mercado de petróleo ao capital estrangeiro. Nos debates, foi o General Horta quem fez a defesa fervorosa do monopólio estatal.</p>
            <p>Em 21 de abril de 1948, um ato no Automóvel Clube do Rio marcava a ampla rejeição dos brasileiros ao projeto do Estatuto do Petróleo, que abria o mercado. Nascia ali o Centro de Estudos e Defesa do Petróleo. A entidade civil reuniu militares, civis, intelectuais, estudantes e trabalhadores em torno da campanha do “petróleo é nosso”. O centro era presidido pelo General Felicíssimo Cardoso, chamado de “General do Petróleo”. Era tio de Fernando Henrique Cardoso.</p>
            <p>Quando Getúlio Vargas iniciou seu segundo governo, em 1951, o movimento de opinião pública tinha preparado o terreno para o projeto de lei que viria a dar vida à Petrobrás. Entre 1951 e 1953, o país assistiu a um intenso debate sobre a conveniência de se criar uma empresa para explorar e refinar o petróleo. Até que, em 21 de setembro de 1953, a Câmara aprovou o projeto. Nascia a Petrobras, empresa de capital misto, com controle da União. A Lei 2004 foi sancionada por Getúlio em 3 de outubro de 1953. Seis meses depois, em 10 de maio de 1954, a Petrobras entrava em atividade. Herdava do Conselho Nacional do Petróleo, criado nos anos 30 pelo Exército, poucos campos de petróleo, com capacidade de produção diária de 2.700 barris, além da refinaria de Mataripe, que processava 2,5 mil barris por dia.</p>
            <p>Quando Getúlio se suicidou, dali a três meses, pressentia que estava em jogo o destino da nação, cujas reservas de petróleo já eram alvo da cobiça de interesses estrangeiros. Na sua carta de despedida, em que diz sair da vida para entrar na história, aponta: “Quis criar a liberdade nacional na potencialização das nossas riquezas através da Petrobras, mal começa esta a funcionar a onda de agitação se avoluma. A Eletrobrás foi obstaculada até o desespero. Não querem que o trabalhador seja livre, não querem que o povo seja independente”.</p>
            <p>Nos anos 70, em plena ditadura militar, sob a liderança do General Ernesto Geisel, a Petrobras deu outro salto. Além de prospecção, produção e refino, transformou a insuficiência em superávit. Geisel implementou a política de conteúdo nacional, por meio do fortalecimento das compras internas. Com isso, milhares de empresas nacionais se desenvolveram. Na administração deste general, construiu-se mais refinarias e começou a exploração em “águas profundas”, que resultou nos anos 2000 na descoberta do pré-sal pelo governo Lula.</p>
            <p><strong>SILÊNCIO DA CASERNA</strong></p>
            <p>A amarga ironia dos nossos tempos é que os militares, defensores da criação da Petrobras e que lutaram – dentro e fora do governo e do Brasil – em defesa dos interesses nacionais, hoje estão calados quanto ao destino do país e da empresa. Não se sabe o que generais pensam da venda de ativos da Petrobras – das  refinarias aos gasodutos, passando pela distribuidora – ou do desmanche da empresa, cuja política de preços com paridade no dólar é uma afronta à soberania. Nem mesmo o que pensam da venda da Eletrobrás.</p>
            <p>Jair Bolsonaro, que nos anos 90 era crítico à quebra do monopólio do petróleo aprovada por Fernando Henrique Cardoso, hoje tem o neoliberalismo como bandeira. O capitão do Exército é quem mantém no seu ministério um grupo de economistas que aposta no neoliberalismo tardio, moldado pela Escola de Chicago, incapaz de acenar com dias melhores para o povo. O mesmo governo que mantém inalterado o status quo, remunerando os mais ricos, mantendo o país com a maior concentração de renda do planeta e as mais elevadas taxas de desigualdade entre todas as democracias. É triste que seja assim. Difícil encarar o fato de que o Exército do General Horta, do General Felicíssimo e do General Geisel, de tanto nacionalismo, esteja silente ante os desmandos e os ataques à soberania nacional.</p>
            <p><strong>A SOLUÇÃO NA CELA</strong></p>
            <p>Nos 65 anos da morte de Getúlio, o Brasil parece retroceder no tempo. Neste dia 24 de agosto, o mais notório sucessor e herdeiro de Getúlio, o metalúrgico Luiz Inácio Lula da Silva, hoje o mais influente político brasileiro no mundo, está preso injustamente, condenado sem provas e em um processo que, sabe-se agora, por conta do The Intercept Brasil, repleto de ilegalidades, vícios e fraudes. Daí que é preciso denunciar os ataques à soberania e dizer que a solução para o país está numa cela. Lula está preso, mas não está morto.</p>
            <p>Em setembro, o país assistirá a um grande ato em defesa da soberania nacional, como em outros momentos da nossa história, quando os democratas estarão mais uma vez reunidos. Líderes políticos, partidos, parlamentares, estudantes, trabalhadores, militantes sociais e representantes de entidades da sociedade civil vão lançar a Frente em Defesa da Soberania Nacional.</p>
            <p>A luta contra os desmandos nos obriga a nos mantermos alertas e firmes. Não percamos a esperança.</p>
            <p>Viva Getúlio Vargas! Viva Lula! Viva o povo brasileiro!</p>
        </section>
    )
}

export default Historia5