import styles from './Historia2.module.css'
import monteiro from '../../img/monteiro.png'


function Historia2(){
    return(
        <section className={styles.home_container}>
            <h1>Monteiro Lobato x Getúlio Vargas: a batalha do petróleo</h1>
            <p>
                <img src={monteiro} alt="O escritor Monteiro Lobato. À esquerda, entrevista sua sobre o petróleo ao jornal Correio de S.Paulo"></img>
                <p></p>
                <p>O nome da cidade nada tem a ver com o criador do Sítio do Pica-Pau-Amarelo, mas é interessante pensar como o destino pode, de fato, ser sábio: Monteiro Lobato foi um dos maiores nomes da luta pelo petróleo de solo brasileiro. Liberal, dedicou-se a criticar dura e abertamente o Código de Minas de 1934. Já sem a herança do avô e sem sua editora, apostava na descoberta do petróleo todas as suas forças – que pareciam mais numerosas que suas moedas.</p>

                <p>No mesmo ano do novo Código de Minas, Lobato se envolveu mais ativamente na pesquisa e na prospecção do petróleo. Boa parte dessa empreitada está documentada numa intensa troca de cartas, ao longo de três anos, entre ele e o engenheiro de perfuração Charles Frankie, imigrado da Suíça em 1920. Os documentos estão depositados no Cedae (Centro de Documentação Alexandre Eulalio), da Unicamp.</p>

                <p>Na correspondência, Lobato fazia críticas contundentes à legislação que acabara de entrar em vigor e ao “atraso brasileiro”. Destacava nas cartas a história das primeiras companhias petrolíferas no país. Em outras mensagens, entraram em discussão questões acerca da parceria na tradução e na redação do prefácio de A Luta pelo Petróleo (1935), de Essad Bey. Mais à frente, esse conjunto de cartas também teria papel definitivo na composição de seu best-seller O Escândalo do Petróleo (1936) e no infantil O Poço do Visconde (1937).</p>

                <p>Entre 1934 e 1936, Lobato empreendeu diversas missões em busca de petróleo, todas frustradas. Seguia criticando a legislação e chegou a apelar para autoridades, na tentativa de alterar o Código de Minas, para que fosse “o mais liberal possível”. Na visão dele, havia pelo menos dois grupos estrangeiros interessados no petróleo brasileiro, mencionados em muitas das cartas: os norte-americanos – que teriam “interesses ocultos”, representados por Vitor Oppenheim e pela Standard Oil – , e os alemães, representados por Frankie e pela empresa Piepmeyer, entre outros.</p>

                <p>Supondo que poderia levar o Brasil a um tipo de desenvolvimento semelhante ao observado nos Estados Unidos e ainda se firmar como empresário e empreendedor, Lobato iniciou a Campanha do Petróleo.</p>

                <p>Nos anos 1930, o mundo ainda não se reerguera da 1ª Guerra Mundial, mas já sofria os efeitos do colapso da Bolsa de Nova York. Nesse cenário, o petróleo passava a ser um valioso e disputado produto. O Brasil, por muito tempo monoexportador de café, sentia as consequências da crise econômica e via sua demanda pelo “ouro negro” dos subsolos crescer fortemente. Em 1932, o país consumia cerca de 12 mil barris por dia; em 1938, exigia a importação de 38 mil barris diários – hoje, o consumo brasileiro gira em torno de 2 milhões de barris por dia.</p>

                <p>Naquele período, o governo federal, buscando fortalecimento estatal, passou a legislar sobre a exploração das riquezas minerais em nome dos interesses da União. Chamou para si o planejamento e a execução dos serviços correspondentes. Em decorrência disso, em 1932 passou a funcionar legalmente no Brasil a Companhia Brasileira de Petróleo, associada à americana Royal Dutch & Shell, referência mundial na extração.</p>

                <p>Lobato, que chegara havia pouco de uma temporada de quatro anos como adido comercial nos Estados Unidos e que já havia escrito seu livro Ferro, entendia o que se passava nessa associação. Assim, entre 1932 e 1935, outras duas companhias passaram a atuar no Brasil: a Companhia Petróleo Nacional, incorporada por Monteiro Lobato, Lino Moreira e Edson de Carvalho, que funcionava legalmente em Riacho Doce, Alagoas; e a Companhia Petróleos do Brasil, presidida por Lobato, instalada legalmente no campo de Araquá, hoje Águas de São Pedro, no interior de São Paulo.</p>

                <p>Ainda assim, não se extraía petróleo do subsolo brasileiro. Ao menos não oficialmente. Em 1933, o Serviço Geológico e Mineralógico do Brasil, braço do Ministério da Agricultura, Indústria e Comércio, que marcara a entrada do Estado no setor petrolífero, foi extinto. O órgão atuara de 1919 até aquele momento, realizando pouquíssimas perfurações (cerca de 50) e em apenas sete estados: Alagoas, Bahia, Pará, Paraná, Rio Grande do Sul, Santa Catarina e São Paulo.</p>

                <p>Nesse mesmo' ano, o Ministério da Agricultura contratou o técnico americano Victor Oppenheim, conhecido e renomado geólogo da época vinculado à Standard Oil, o maior truste petrolífero norte-americano, para operar pesquisas em solo brasileiro. Lobato, então, começou a criticar publicamente a associação entre o governo brasileiro e a estrutura empresarial dos Estados Unidos.</p>

                <p>Em paralelo, Juarez Távora, na pasta da Agricultura, solicitava oficialmente ao Itamaraty uma organização do exterior para estudos geofísicos no Brasil. O órgão indicou-lhe a firma alemã Piepmeyer & Co.</p>

                <p>Em março de 1934, o DNPM (Departamento Nacional da Produção Mineral) foi criado – extinto em dezembro de 2018, foi substituído pela Agência Nacional de Mineração – , e sua presidência ficou com Fleury da Rocha, contra quem Lobato travaria longa batalha. O órgão passou a comandar as iniciativas de pesquisa de petróleo em território brasileiro.</p>

                <p>Pouco depois disso, Victor Oppenheim começou a divulgar os primeiros resultados de sua pesquisa. Em boletim ao DNPM, afirmava: “A região de S. Pedro, no estado de São Paulo [poço São João do Araquá, cuja exploração se dava pela Companhia Petróleos do Brasil, de Monteiro Lobato] é, do ponto de vista geológico-estratigráfico, francamente negativa para futuras pesquisas de petróleo nessa região”.</p>

                <p>Em Alagoas, em um poço da Companhia Petróleo Nacional, outra empresa de Lobato, o estudo de Oppenheim também contrariava a crença no petróleo litorâneo. Mais tarde, isso viria a ser desmentido por técnicos alemães próximos ao escritor. Era claro o esforço de Oppenheim, representante do Estado, em negar a existência de petróleo onde Lobato bradava o oposto de forma visceral.</p>

                <p>No Boletim de Agricultura, Oppenheim publicara, também, trechos de seu relatório sobre a região de Lobato, “A Questão do Petróleo da Bahia”. Na página 93, afirmava: “Esta localidade [Lobato, BA], do ponto de vista da geologia de petróleo, é positivamente desfavorável à presença de hidrocarbonetos. O conjunto geotectônico desse local é absolutamente negativo. Os elementos técnicos atestam de um modo formal a não existência de jazidas petrolíferas […]. Está provada à sociedade a inexistência de depósitos petrolíferos no lugar denominado Lobato na Bahia”. Em janeiro de 1939, contudo, o oposto ficaria provado à sociedade, com o anúncio oficial da descoberta do primeiro poço de petróleo brasileiro nessa mesma região.</p>

                <p>Com o objetivo de “remover obstáculos e embaraços ao racional aproveitamento das riquezas do subsolo” e de assegurar “as iniciativas privadas nos trabalhos de pesquisa e lavra”, em 1934 o governo federal promulgou o novo Código de Minas, que regulava a propriedade das jazidas do subsolo. Com ele, a posse das riquezas minerais tornou-se independente da posse do solo: aquelas se tornaram propriedade da União, e sua exploração passou a demandar concessão especial do governo federal. Tal dispositivo estava alinhado à Constituição de 1934, promulgada seis dias depois.</p>

                <p>A nova legislação também estabelecia “a nacionalização das jazidas e minas julgadas básicas ou essenciais à defesa econômica ou militar do país” e “a exigência de nacionalidade brasileira ou de constituição de uma empresa nacional para atuar no setor de mineração” – medidas nitidamente nacionalistas. Lobato, como já dito, combateria extensivamente, como escritor e empresário, o Código de Minas. Irritado em especial com a exigência de nacionalidade brasileira para a pesquisa e para a lavra das jazidas minerais, apelidou-o de “lei cipó”.</p>

                <p>A legislação, porém, ao definir empresas nacionais como “sociedades organizadas no Brasil”, sem restrição de nacionalidade dos acionistas, possibilitava que companhias estrangeiras fossem até proprietárias de empresas nacionais. Lobato usou essa brecha para organizar no Brasil sociedades com capital estrangeiro, como foi o caso da Amep (Aliança Mineração e Petróleos), que consolidou a união entre o autor-empresário e os alemães. Ele não permitiria que o petróleo brasileiro ficasse exclusivamente com o truste americano Standard Oil-Royal Dutch , que o escritor imaginava estar por trás do imbróglio, sem oferecer uma concorrência mínima.</p>

                <p>Crítico da exclusividade da pesquisa e da lavra das jazidas de petróleo por empresas brasileiras, Lobato avaliava, simultaneamente, que empresas americanas buscavam abarcar terras no Brasil com o propósito de garantir prioridade no futuro (Isso não aconteceu, uma vez que, em 1953, todas as atividades de pesquisa, exploração, refino e transporte de petróleo no Brasil tornaram-se monopólio da União, o que vigorou até 1997.)</p>

                <p>Lobato julgava necessária a diferenciação entre acordo e entreguismo. Ele cobrava que Getúlio Vargas priorizasse os interesses do Estado brasileiro, inclusive em longo prazo. O escritor era um cidadão inconformado que não desistia de exercer seus direitos políticos, um intelectual apaixonado que caminhava rumo a seu propósito, atuando nas mais diversas áreas: alimentava debates na imprensa, discursava acerca da importância dos empreendimentos nacionais, realizava prospecção de petróleo, escrevia artigos e livros sobre o tema e dedicava-se visceralmente aos “bastidores do petróleo”, pela intensa troca de cartas, buscando os mais diversos arranjos políticos e comerciais.</p>

                <p>Mais que um escritor, Monteiro Lobato era um intelectual apaixonado e devoto do poder da literatura e dos livros. Cabe aqui uma reflexão sobre o essencial papel que o verdadeiro pensador desempenha no processo de desenvolvimento de uma população. O intelectual que fala com todos é essencial em tempos obscuros.</p>

                <p>Homens e mulheres como Monteiro Lobato, Sérgio Buarque de Holanda, Rachel de Queiroz, Anísio Teixeira, Bertha Lutz, Antonio Candido, Paulo Freire, Conceição Evaristo, Milton Santos, entre tantos pensadores, são, antes de mais nada, cidadãos brasileiros inconformados com o que viam como injustiças, diante do que canalizaram suas angústias na desafiadora tarefa de colocar seus contemporâneos a pensar a respeito de dimensões fundamentais da existência humana em uma sociedade política.</p>

                <p>Uma dessas incursões de Lobato é narrada em uma comovente carta de 1º de maio de 1935 a Frankie. Ao lamentar a ignorância de deputados e senadores sobre a questão do petróleo e abrir mão de seus direitos autorais para distribuir livros sobre o tema no Congresso, afirma convicto, ainda que magoado, que apenas o livro seria capaz de levar lucidez à cena: “O livro [A Luta pelo Petróleo] é que vai abrir os olhos dessa gente, mostr

                ando-lhe que não temos só o petróleo, mas toda a técnica e todo o sistema econômico dos Estados Unidos. Não serão estas sementinhas de livre-economia [livre mercado] que atingirão os bichos-carpinteiros. Atiraremos em vão na horta deles: eles voam”. Em carta de outubro do mesmo ano, insiste: “O Petróleo tem de ser batalha de opinião e o único meio é o livro”.</p>

                <p>Com efeito, já nas primeiras páginas de O Escândalo do Petróleo, Lobato faz questão de mencionar, na introdução, que não se trata de um romance, mas de um documento histórico. O autor-empresário e o homem público, que integrou a campanha de uma aliança entre Luís Carlos Prestes e Getúlio Vargas à presidência da República, lançava-se em um novo desafio: o de historiador. O homem que se esmerou em criar uma literatura infantil brasileira unicamente nossa, absolutamente brasileira, agora esmerava-se na busca de fontes, documentos, provas, indícios e informações que sustentassem suas teses e suas análises históricas acerca do petróleo no Brasil.</p>

                <p>Em 1939, a Companhia Petróleos do Brasil (de Lobato) encontrou petróleo. No ano seguinte, lançou o livro O Poço do Visconde, infantil. Nele, a história se inicia quando Tia Anastácia, ao tentar iluminar o sítio com uma vela, causa um incêndio. Assustado, o Visconde pede que se interrompa a escavação do poço, iniciada por ele, e se preencha o buraco com terra, a fim de apagar o fogo. No entanto, Dona Benta, que conhecera o avô de Anastácia, mantém-se firme no propósito: o poço deverá ser aceso, afinal seu objetivo é encontrar petróleo e não água.</p>

                <p>Um paralelo pode ser feito entre a petroleira de Lobato e o Visconde de Sabugosa, ambos pioneiros em seus propósitos: o personagem procura o petróleo em terras do Sítio do Picapau Amarelo, assim como Lobato, enquanto empresário, no Brasil. Em termos reais, Lobato também cavava um poço em terras brasileiras, buscando o petróleo. Em 1939, por meio da Companhia Petróleos do Brasil, o escritor encontrou petróleo em Lobato, no interior de São Paulo.</p>

                <p>Lobato não era geólogo e não tinha formação específica na área de exploração de petróleo, mas se dedicou intensamente ao estudo e à pesquisa sobre o assunto. Ele acreditava que o Brasil tinha potencial para ser autossuficiente na produção de petróleo e que essa riqueza natural poderia impulsionar o desenvolvimento do país de forma independente. Suas cartas, artigos e livros sobre o tema refletem seu engajamento e seu desejo de ver o Brasil controlando suas próprias reservas de petróleo.</p>

                <p>Em última análise, Monteiro Lobato foi muito mais do que apenas o criador de histórias encantadoras para crianças. Ele foi um cidadão ativo, um empresário determinado e um pensador crítico que buscou incansavelmente promover o desenvolvimento do Brasil por meio da valorização de seus recursos naturais e da defesa de uma política econômica que beneficiasse o país. Sua atuação na questão do petróleo é apenas um exemplo do papel que intelectuais engajados podem desempenhar na construção de um país melhor.</p>

                <p>Além de sua influência na questão do petróleo, Monteiro Lobato também teve um impacto significativo na literatura brasileira e na promoção da leitura. Ele é amplamente reconhecido por suas obras de literatura infantil, como a série "Sítio do Picapau Amarelo", que cativou gerações de leitores brasileiros. Suas histórias misturavam elementos da cultura brasileira com fantasia e aventura, estimulando a imaginação das crianças e incentivando o gosto pela leitura.</p>
                <p>Como um defensor fervoroso da educação e da cultura, Lobato acreditava que os livros tinham o poder de transformar mentes e moldar o futuro do país. Ele foi um crítico da falta de investimento em educação no Brasil e frequentemente se envolveu em debates sobre políticas educacionais. Sua dedicação à literatura infantil e à promoção da leitura como ferramentas de desenvolvimento intelectual e social são evidentes em seu legado.</p>
                <p>Mesmo depois de sua morte, em 1948, Monteiro Lobato continuou a influenciar gerações de escritores, educadores e leitores. Seu compromisso com a transformação do Brasil por meio da educação, do acesso à informação e do desenvolvimento econômico permanece como um exemplo inspirador de como um indivíduo pode fazer a diferença em sua sociedade.</p>
                <p>Portanto, a trajetória de Monteiro Lobato, marcada por sua atuação multifacetada como escritor, empresário, defensor da educação e pensador crítico, é um reflexo do poder da paixão, da dedicação e do engajamento em causas que transcendem os limites da literatura e da cultura, impactando diretamente a sociedade e a nação como um todo.</p>            
            </p>
        </section>
    )
}

export default Historia2